image:
  - Visual Studio 2017
  - Ubuntu1804

stack: python 3

environment:
  PY_DIR: C:\Python37-x64

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

clone_depth: 1

install:
  - sh: sudo apt-get -y update && sudo apt-get -y install python3.7-dev
  - pip install pipenv
  - pipenv sync --dev

build_script:
  - sh: pipenv run pyinstaller onefile.spec
  - cmd: pipenv run pyinstaller win_onefile.spec

artifacts:
  - path: dist/autograder_linux
    name: autograder_linux

  - path: dist/autograder.exe
    name: autograder_win

deploy:
  - provider: GitHub
    auth_token:
      secure: N/sHELjf8E0NwZ8Wtxfyqa8afsXCBBOvsiCyfDWSy8ocl85Js25NwLg/bInU8jj3
    description: ''
    artifact: autograder_linux, autograder_win
    draft: false
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
