output_dir = "out"

[build]
source_dir = "src"
# array of file, dest pairs that define files stored in .lib, and where they should be copied to
# secret is true by default, meaning the file will be deleted after testing is complete
required_files = [ { file = 'ComplexTests.class', dest = 'out/p05' } ]
commands = [ 'javac -d out src/p05/Complex.java src/p05/EX13_17.java' ]

[[test]]
name = "JUnit testing"
type = "junit"
classname = "p05.ComplexTests"

[[test]]
name = "Diff 1"
type = "diff"
points = 20
command = "java p05.EX13_17"
input = "1 1 2 2"
expected = "output.txt" 